
# Generated by Django 5.1 on 2025-01-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blog_alter_comment_food_delete_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='food',
            new_name='blog',
        ),
    ]
